export const options = [
    {title: 'The Shawshank Redemption', year: 1994, group: 'programming'},
    {title: 'The Godfather', year: 1972, group: 'programming'},
    {title: 'The Godfather: Part II', year: 1974, group: 'programming'},
    {title: 'The Dark Knight', year: 2008, group: 'programming'},
    {title: '12 Angry Men', year: 1957, group: 'programming'},
    {title: "Schindler's List", year: 1993, group: 'programming'},
    {title: 'Pulp Fiction', year: 1994, group: 'designing'},
    {title: 'The Lord of the Rings: The Return of the King', year: 2003, group: 'designing'},
    {title: 'The Good, the Bad and the Ugly', year: 1966, group: 'designing'},
    {title: 'Fight Club', year: 1999, group: 'designing'},
    {title: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001, group: 'designing'},
    {title: 'Star Wars: Episode V - The Empire Strikes Back', year: 1980, group: 'designing'},
    {title: 'Forrest Gump', year: 1994, group: 'designing'},
    {title: 'Inception', year: 2010, group: 'designing'},
    {title: 'The Lord of the Rings: The Two Towers', year: 2002, group: 'writing'},
    {title: "One Flew Over the Cuckoo's Nest", year: 1975, group: 'writing'},
    {title: 'Goodfellas', year: 1990, group: 'writing'},
    {title: 'The Matrix', year: 1999, group: 'writing'},
    {title: 'Seven Samurai', year: 1954, group: 'teaching'},
    {title: 'Star Wars: Episode IV - A New Hope', year: 1977, group: 'teaching'},
    {title: 'City of God', year: 2002, group: 'teaching'},
    {title: 'Se7en', year: 1995, group: 'teaching'},
    {title: 'The Silence of the Lambs', year: 1991, group: 'teaching'},
    {title: "It's a Wonderful Life", year: 1946, group: 'teaching'},
    {title: 'Life Is Beautiful', year: 1997, group: 'teaching'},
    {title: 'The Usual Suspects', year: 1995, group: 'teaching'},
    {title: 'Léon: The Professional', year: 1994, group: 'teaching'},
    {title: 'Spirited Away', year: 2001, group: 'gaming'},
    {title: 'Saving Private Ryan', year: 1998, group: 'gaming'},
    {title: 'Once Upon a Time in the West', year: 1968, group: 'gaming'},
    {title: 'American History X', year: 1998, group: 'gaming'},
    {title: 'Interstellar', year: 2014, group: 'gaming'},
];